/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swinggui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author HAKHENG
 */
public class frmAdminMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmAdminMain() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUserManagement = new javax.swing.JMenuItem();
        menuGroupManagement = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCustomer = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        menuProduct = new javax.swing.JMenu();
        menuCategory = new javax.swing.JMenuItem();
        menuRecord = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSale = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuPurchase = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(50, 35));

        menuUserManagement.setText("User Management");
        menuUserManagement.setPreferredSize(new java.awt.Dimension(145, 40));
        menuUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserManagementActionPerformed(evt);
            }
        });
        jMenu1.add(menuUserManagement);

        menuGroupManagement.setText("Group Management");
        menuGroupManagement.setPreferredSize(new java.awt.Dimension(145, 40));
        jMenu1.add(menuGroupManagement);
        jMenu1.add(jSeparator1);

        menuLogout.setText("Logout");
        menuLogout.setPreferredSize(new java.awt.Dimension(145, 40));
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuExit.setText("Exit");
        menuExit.setPreferredSize(new java.awt.Dimension(145, 40));
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(50, 35));

        menuCustomer.setText("Customer");
        menuCustomer.setPreferredSize(new java.awt.Dimension(145, 40));
        jMenu2.add(menuCustomer);

        menuSupplier.setText("Supplier");
        menuSupplier.setPreferredSize(new java.awt.Dimension(145, 40));
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(menuSupplier);

        menuProduct.setText("Product");
        menuProduct.setPreferredSize(new java.awt.Dimension(145, 40));

        menuCategory.setText("Category");
        menuCategory.setPreferredSize(new java.awt.Dimension(145, 35));
        menuCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoryActionPerformed(evt);
            }
        });
        menuProduct.add(menuCategory);

        menuRecord.setText("Record");
        menuRecord.setPreferredSize(new java.awt.Dimension(145, 35));
        menuRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecordActionPerformed(evt);
            }
        });
        menuProduct.add(menuRecord);

        jMenu2.add(menuProduct);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaction");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(145, 40));

        menuSale.setText("Sale");
        menuSale.setPreferredSize(new java.awt.Dimension(145, 40));

        jMenuItem9.setText("Sale Order");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(145, 35));
        menuSale.add(jMenuItem9);

        jMenuItem10.setText("Sale Delivery");
        jMenuItem10.setPreferredSize(new java.awt.Dimension(145, 35));
        menuSale.add(jMenuItem10);

        jMenuItem11.setText("Sale Invoice");
        jMenuItem11.setPreferredSize(new java.awt.Dimension(145, 35));
        menuSale.add(jMenuItem11);

        jMenuItem12.setText("Debit Note");
        jMenuItem12.setPreferredSize(new java.awt.Dimension(145, 35));
        menuSale.add(jMenuItem12);

        jMenu3.add(menuSale);

        menuPurchase.setText("Purchase");
        menuPurchase.setPreferredSize(new java.awt.Dimension(145, 40));

        jMenuItem13.setText("Purchase Order");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(145, 35));
        menuPurchase.add(jMenuItem13);

        jMenuItem14.setText("Puchase Delivery");
        jMenuItem14.setPreferredSize(new java.awt.Dimension(145, 35));
        menuPurchase.add(jMenuItem14);

        jMenuItem15.setText("Purchase Invoice");
        jMenuItem15.setPreferredSize(new java.awt.Dimension(145, 35));
        menuPurchase.add(jMenuItem15);

        jMenuItem16.setText("Credit Note");
        jMenuItem16.setPreferredSize(new java.awt.Dimension(145, 35));
        menuPurchase.add(jMenuItem16);

        jMenu3.add(menuPurchase);

        menuStock.setText("Stock");
        menuStock.setPreferredSize(new java.awt.Dimension(145, 40));

        jMenuItem17.setText("Stock Adjustment");
        jMenuItem17.setPreferredSize(new java.awt.Dimension(145, 35));
        menuStock.add(jMenuItem17);

        jMenuItem18.setText("Stock Count");
        jMenuItem18.setPreferredSize(new java.awt.Dimension(145, 35));
        menuStock.add(jMenuItem18);

        jMenu3.add(menuStock);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUserManagementActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void menuCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoryActionPerformed

    private void menuRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRecordActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
        frmLogin login = new frmLogin();
        login.setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = screenSize.width / 2;
        int centerY = screenSize.height / 2;
        login.setLocation(centerX - login.getWidth() / 2, centerY - login.getHeight() / 2);
    });

    // Close the current login form
    this.dispose();
    }//GEN-LAST:event_menuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCategory;
    private javax.swing.JMenuItem menuCustomer;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuGroupManagement;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuProduct;
    private javax.swing.JMenu menuPurchase;
    private javax.swing.JMenuItem menuRecord;
    private javax.swing.JMenu menuSale;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenuItem menuSupplier;
    private javax.swing.JMenuItem menuUserManagement;
    // End of variables declaration//GEN-END:variables
}
